### ISSUE TITLE
Initial dialog flow

### ISSUE THREAD

**Issue by RossellaFer** [CBID2/ChatBot#3]
- onMembersAdded (in `dialogBot.js`) displays the initial welcome message and image. However, in order to start the waterfall dialogue, I had to add some welcome text that asks the user to type in something to go forward
- in `userProfileDialog.js`, there are some options that should require the user to type if the most appropriate option is not in the list, for example

  > Chabot: Great [user’s name]! I can help you with that! :) Now what sector do you work in?
  > Non-profit
  > Education
  > [Type Here] 
  > 
  > Chatbot: Great [user’s name]! Where do you live?
  > USA.
  > Africa
  > Caribbean 
  > Other

  Not sure on how to branch out the dialogue to allow some text prompt

**Comment by loftwah** [comment]
We should be able to use the Google doc as a reference.

**Comment by loftwah** [comment]
I don't think we need a GitHub issue for this. We've done the dialogue between Google Docs and Discord. What do you think?
